### ISSUE TITLE
Outland's TODO List

### ISSUE THREAD

**Issue by FALL1N1** [FALL1N1/TBC_New#2]
Test, assign scripts and release a "stable" branch.

> Arenas
- [x] Ring of Trials
- [x] Circle of Blood
- [x] Ruins of Lordaeron

> Battlegrounds 
- [x] Warsong Gulch
- [x] Arathi Basin
- [x] Alterac Valley
- [x] Eye of the Storm

> Dungeons
- [x] Hellfire Ramparts	
- [x] Blood Furnace
- [x] Slave Pens	
- [x] Underbog	
- [x] Mana-Tombs	
- [x] Auchenai Crypts	
- [x] Escape from Durnholde Keep	
- [x] Sethekk Halls	
- [x] Shadow Labyrinth	
- [x] Shattered Halls	
- [x] The Botanica	
- [x] The Mechanar	
- [x] The Steamvault	
- [x] Magisters' Terrace	  
- [x] The Arcatraz	  
- [x] The Black Morass /Opening of the Dark Portal/

> Raids
- [x] Karazhan
- [x] Gruul's Lair
- [x] Magtheridon's Lair
- [x] Zul'Aman
- [x] Serpentshrine Cavern
- [x] Tempest Keep: The Eye
- [x] Battle for Mount Hyjal
- [x] Black Temple
- [x] Sunwell Plateau
